version: '3'

services:
  apiserver:
    build: ./docker/node
    image: express
    tty: true
    volumes:
      - ./:/var/www
    ports:
      - 8080:3000
    environment:
      NODE_ENV: development
