version: '3'

services:
  express:
    build: ./docker/node
    image: investment-support-api:express
    container_name: app
    tty: true
    volumes:
      - ./:/var/www
    ports:
      - 8080:3000
    depends_on:
      - mysql

  mysql:
    build: ./docker/mysql
    image: investment-support-api:mysql5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
