version: '3'

services:
  express:
    build: ../node/docker
    image: skys-api:app
    container_name: app
    tty: true
    volumes:
      - ./:/var/www
    ports:
      - 8080:3000
    depends_on:
      - mysql

  mysql:
    build: ../mysql/docker
    image: skys-api:mysql5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    volumes:
      - ../mysql/docker/initdb.d:/docker-entrypoint-initdb.d
      - ../mysql/docker/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
